//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyService.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Core.Objects.DataClasses;
    using System.Linq;
    
    public partial class SampleEntities : DbContext
    {
        public SampleEntities()
            : base("name=SampleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Employee> Employees { get; set; }
        public DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<PROC_Importent_Result> PROC_Importent(string test)
        {
            var testParameter = test != null ?
                new ObjectParameter("Test", test) :
                new ObjectParameter("Test", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_Importent_Result>("PROC_Importent", testParameter);
        }
    
        public virtual ObjectResult<PROC_Users_Result> PROC_Users()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_Users_Result>("PROC_Users");
        }
    }
}
